version: "3.7"

services:
  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
  ruby_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: ruby_container_test
    environment:
      - "RAILS_ENV=test"
      - "SELENIUM_HOST_URL=http://chrome:4444/wd/hub"
      - "TEST_APP_HOST=ruby_test"
      - "TEST_APP_PORT=3001"
      - "ROOT_URL=http://ruby_test:3001"
      - "RAILS_SERVE_STATIC_FILES=true"
  chrome:
    image: selenium/standalone-chrome-debug
    environment:
      - "JAVA_OPTS=-Dselenium.LOGGER.level=OFF"
