version: "3.7"

services:
  postgres:
    image: postgres:12.5
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
  ruby_dev:
    build: .
    container_name: ruby_container_dev
    ports:
      - "8080:3000"
      - "3001:3001"
      - "3035:3035"
    volumes:
      - .:/home/app
      - bundler_gems:/usr/local/bundle/ # save so we don't have to keep running bundle install in development
    environment:
      - "SELENIUM_HOST_URL=http://chrome:4444/wd/hub"
      - "TEST_APP_HOST=ruby_dev"
      - "TEST_APP_PORT=3001"
      - "ROOT_URL=http://localhost:8080"
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"

volumes:
  bundler_gems:
