version: "3.7"

services:
  postgres:
    image: postgres:12.5
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
  ruby_dev:
    build: .
    container_name: ruby_container
    ports:
      - "8080:3000"
      - "3035:3035"
    volumes:
      - .:/home/app
      - bundler_gems:/usr/local/bundle/ # save so we don't have to keep running bundle install in development

volumes:
  bundler_gems:
